# https://www.mkdocs.org/user-guide/configuration/
site_name: 🥐 croissant-go Docs
site_description: "Documentation for the 🥐 croissant-go tool"
site_author: B13rg
theme:
  name: readthedocs
  locale: en
  color_mode: dark
  user_color_mode_toggle: true

repo_url: https://github.com/b13rg/croissant-go/
site_dir: ./_site
docs_dir: ./docs
edit_uri: blob/main/docs
exclude_docs: |
  *.go

nav:
  - Home: index.md
  - Repo Readme: README-repo.md
  - Commands:
    - root: cmd/croissant.md
    - version: cmd/croissant_version.md
  - Godocs:
    - version: godoc/croissant-cmd.md
    - types: godoc/croissant-types.md 

